public enum CategoriasEnum {
    LIMPEZA,
    CONGELADOS_E_FRIOS,
    HORTIFRUTI,
    HIGIENE_PESSOAL,
    BEBIDAS,
    PAPELARIA,
    PADARIA,
    MERCEARIA_EM_GERAL,
    CARNES,
    UTILIDADES,
    OUTROS;
}
